upstream ${UPSTREAM_NAME} {
    server ${BACKEND};
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    
    server_name ${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;

    # Use the backend-provided icon if available
    location = /favicon.ico {
        proxy_pass http://${UPSTREAM_NAME};
        include snippets/proxy-headers-https.conf;
        proxy_intercept_errors on;

        error_page 404 = @favicon_fallback;
    }

    # Otherwise serve the generic icon
    location @favicon_fallback {
        internal;
        root /var/www/html/static;
        try_files /favicon.ico =404;
    }

    # Main proxy location
    location / {
        proxy_pass http://${UPSTREAM_NAME};
        include snippets/proxy-headers-https.conf;
    }
}
